version: '1'
services:
  redis:
    image: "redis:3.0.6"
    ports:
    - "6379:6379"
  cassandra:
    image: "cassandra:3.0"
    ports:
    - "9042:9042"
  mysql:
    image: "mysql:5.7"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EZPing
  rabbitmq-stomp:
    image: "byteflair/rabbitmq-stomp:3.6"
    ports:
    - "5672:5672"
    - "15672:15672"
    - "61613:61613"