version: '3'
services:
  redis:
    image: "redis:3.0.6"
    ports:
    - "6379:6379"
  cassandra:
    image: "cassandra:3.0"
    ports:
    - "9042:9042"
  mysql:
    image: "mysql:5.7"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EZPing
  rabbitmq-stomp:
    image: "byteflair/rabbitmq-stomp"
    ports:
    - "5672:5672"
    - "15672:15672"
    - "61613:61613"
  nginx:
    image: "nginx"
    volumes:
      - ./ezping.template:/etc/nginx/conf.d/ezping.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ezping.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
